"""empty message

Revision ID: c28e62570eaf
Revises: 0a6ff04ec9f0
Create Date: 2022-12-09 14:19:11.499258

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c28e62570eaf'
down_revision = '0a6ff04ec9f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('car_ibfk_1', 'car', type_='foreignkey')
    op.drop_column('car', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('car_ibfk_1', 'car', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
